playercounter:
  activated: true
  text:
    - "&3Hello world!"
    - "&eNewline!"
    - "&6    spaces!"
    - "&d&lCombined"
    - "&1Players: %real_players%"
    - "&2Max: %real_max%"

overrideonline:
  activated: false
  value: 0

overridemax:
  activated: false
  value: 10

protocol:
  activated: false
  text: "&1My custom protocol message!"

icons:
  activated: false

motd:
  activated: true
  text:
    - "Hello! \n World!"
    - "Use &4color codes!"
    - "&ka &rFormatting &rworks &rtoo! &ka"
    - "&1Players: %real_players%"