# You can find color codes here: https://minecraft.tools/en/color-code.php
# Do newlines with: \n
# Formatting comes after the color! §d§l will work, but not §l§d.

text:
  "§3Hello world! \n§eNewline!\n§6    spaces!\n§d§lCombinded"