overridemax:
  activated: false
  value: 10

motd:
  activated: true
  text:
    - "Hello! %newline%World!"
    - "Use &4color codes!"
    - "&ka &rFormatting &rworks &rtoo! &ka"
    - "&1Players: %online%"
    - "&2Max: %max%"

# Extended config only works on paper https://papermc.io/
extended:
  protocol:
    activated: false
    text: "&1My custom protocol message!"

  overrideonline:
    activated: false
    value: 0

  hideplayers:
    activated: false
    value: true

  playercounter:
    activated: true
    text:
      - "&3Hello world!"
      - "&eNewline!"
      - "&6    spaces!"
      - "&d&lCombined"
      - "&1Players: %online%"
      - "&2Max: %max%"