# You can find color codes here: https://minecraft.tools/en/color-code.php
# Formatting comes after the color! §d§l will work, but not §l§d.
playercounter:
  activated: true
  text:
    - "§3Hello world!"
    - "§eNewline!"
    - "§6    spaces!"
    - "§d§lCombinded"

# Override online players (This only overrides the shown playercount. Its not the real one.)
overrideonline: false
# Online players (Requires override)
online: 0

# Override the max players (This only overrides the shown max limit. Its not the real one.)
overridemax: false
# Max players (Requires override)
max: 10

# Here is a list with all version numbers: https://wiki.vg/Protocol_version_numbers
# You can use a protocol version which doesnt exist to always get a client out of date message in the server list. (Example: 9999)
# This number only means the minimum version required. If the client isn't high enough this custom message gets showed.
# ONLY if the protocol version of the player is at the moment lower than the minimum protocol version the text gets showed.
# You can use %aftericon% to push the text after the favicon. (It just adds many spaces and only works in the protocol text.)
protocol:
  activated: false
  text: "My custom protocol message!"

icons:
  activated: false

motd:
  activated: false
  # You can use only one or over 9999.
  # Same rules as above.
  # Use some multiple times to make a higher chance of getting them.
  # Only one \n allowed.
  text:
    - "Hello! \n World!"
    - "Use §4color codes!"
    - "§ka §rFormatting §rworks §rtoo! §ka"