# You can find color codes here: https://minecraft.tools/en/color-code.php
# Do newlines with: \n
# Formatting comes after the color! §d§l will work, but not §l§d.

playercounter:
  activated: true
  text:
    - "§3Hello world!"
    - "§eNewline!"
    - "§6    spaces!"
    - "§d§lCombinded"

# Override online players (This only overrides the shown playercount. Its not the real one.)
overrideonline: false
# Online players (Requires override)
online: 0

# Override the max players (This only overrides the shown max limit. Its not the real one.)
overridemax: false
# Max players (Requires override)
max: 10

motd:
  activated: false
  # You can use only one or over 9999.
  # Same rules as above.
  # Use some multiple times to make a higher chance of getting them.
  # Only one \n allowed.
  text:
    - "Hello! \n World!"
    - "Use §4color codes!"
    - "§ka §rFormatting §rworks §rtoo! §ka"