name: BungeePing
version: 1.0.0
main: me.alexprogrammerde.BungeePing.Main
author: AlexProgrammerDE
description: A plugin for editing the server list player hover message.
website: https://www.6b6t.org