name: PistonMOTD
version: ${project.version}
api-version: 1.16
main: me.alexprogrammerde.PistonMOTD.bukkit.PistonMOTDBukkit
description: ${project.description}
commands:
  pistonmotd:
    description: Allows you to execute some commands for pistonmotd.
    permission: pistonmotd.command
    aliases: ["pistonmotdbukkit"]

permissions:
  pistonmotd.help:
    description: Permission to have the help menu shown.
    default: op
    children:
      - pistonmotd.command
  pistonmotd.reload:
    description: Permission to reload the motd config.
    default: op
    children:
      - pistonmotd.command
  pistonmotd.command:
    description: Permission to even access the cmd.
    default: op